<?php

namespace ContainerNseTVN5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_QBTLmzjService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.service_locator.QBTLmzj' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.QBTLmzj'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'repo' => ['privates', 'App\\Repository\\TacheRepository', 'getTacheRepositoryService', true],
        ], [
            'repo' => 'App\\Repository\\TacheRepository',
        ]);
    }
}
