<?php

namespace ContainerNseTVN5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_P0zPGcfService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.service_locator.p0zPGcf' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'passwordHasher' => ['privates', 'security.user_password_hasher', 'getSecurity_UserPasswordHasherService', true],
            'slugger' => ['privates', 'slugger', 'getSluggerService', true],
        ], [
            'em' => '?',
            'passwordHasher' => '?',
            'slugger' => '?',
        ]);

        if (isset($container->privates['.service_locator.p0zPGcf'])) {
            return $container->privates['.service_locator.p0zPGcf'];
        }

        return $container->privates['.service_locator.p0zPGcf'] = $instance;
    }
}
