<?php

namespace ContainerNseTVN5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_U0qd4F4Service extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.service_locator.U0qd4F4' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'salle' => ['privates', '.errored..service_locator.U0qd4F4.App\\Entity\\Salle', NULL, 'Cannot autowire service ".service_locator.U0qd4F4": it needs an instance of "App\\Entity\\Salle" but this type has been excluded in "config/services.yaml".'],
        ], [
            'entityManager' => '?',
            'salle' => 'App\\Entity\\Salle',
        ]);

        if (isset($container->privates['.service_locator.U0qd4F4'])) {
            return $container->privates['.service_locator.U0qd4F4'];
        }

        return $container->privates['.service_locator.U0qd4F4'] = $instance;
    }
}
