<?php

namespace ContainerNseTVN5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Y6xNXC6Service extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.service_locator.Y6xNXC6' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'tache' => ['privates', '.errored..service_locator.Y6xNXC6.App\\Entity\\Tache', NULL, 'Cannot autowire service ".service_locator.Y6xNXC6": it needs an instance of "App\\Entity\\Tache" but this type has been excluded in "config/services.yaml".'],
            'tacheRepository' => ['privates', 'App\\Repository\\TacheRepository', 'getTacheRepositoryService', true],
        ], [
            'entityManager' => '?',
            'tache' => 'App\\Entity\\Tache',
            'tacheRepository' => 'App\\Repository\\TacheRepository',
        ]);

        if (isset($container->privates['.service_locator.Y6xNXC6'])) {
            return $container->privates['.service_locator.Y6xNXC6'];
        }

        return $container->privates['.service_locator.Y6xNXC6'] = $instance;
    }
}
