<?php

namespace ContainerNseTVN5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_RmU_XokService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.service_locator.RmU.Xok' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'preferenceAlerte' => ['privates', '.errored..service_locator.RmU.Xok.App\\Entity\\PreferenceAlerte', NULL, 'Cannot autowire service ".service_locator.RmU.Xok": it needs an instance of "App\\Entity\\PreferenceAlerte" but this type has been excluded in "config/services.yaml".'],
        ], [
            'entityManager' => '?',
            'preferenceAlerte' => 'App\\Entity\\PreferenceAlerte',
        ]);

        if (isset($container->privates['.service_locator.RmU.Xok'])) {
            return $container->privates['.service_locator.RmU.Xok'];
        }

        return $container->privates['.service_locator.RmU.Xok'] = $instance;
    }
}
