<?php

namespace ContainerNseTVN5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_M9txnVvService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.service_locator.M9txnVv' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.M9txnVv'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'chartBuilder' => ['privates', 'chartjs.builder', 'getChartjs_BuilderService', true],
            'classe' => ['privates', '.errored..service_locator.M9txnVv.App\\Entity\\Classe', NULL, 'Cannot autowire service ".service_locator.M9txnVv": it needs an instance of "App\\Entity\\Classe" but this type has been excluded in "config/services.yaml".'],
            'statsService' => ['privates', 'App\\Service\\StatsService', 'getStatsServiceService', true],
            'studyCoachService' => ['privates', 'App\\Service\\StudyCoachService', 'getStudyCoachServiceService', true],
            'userRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
        ], [
            'chartBuilder' => '?',
            'classe' => 'App\\Entity\\Classe',
            'statsService' => 'App\\Service\\StatsService',
            'studyCoachService' => 'App\\Service\\StudyCoachService',
            'userRepository' => 'App\\Repository\\UserRepository',
        ]);
    }
}
