<?php

namespace ContainerNseTVN5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Tf_94EiService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.service_locator.tf.94Ei' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'preferenceAlerteRepository' => ['privates', 'App\\Repository\\PreferenceAlerteRepository', 'getPreferenceAlerteRepositoryService', true],
            'userRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
        ], [
            'entityManager' => '?',
            'preferenceAlerteRepository' => 'App\\Repository\\PreferenceAlerteRepository',
            'userRepository' => 'App\\Repository\\UserRepository',
        ]);

        if (isset($container->privates['.service_locator.tf.94Ei'])) {
            return $container->privates['.service_locator.tf.94Ei'];
        }

        return $container->privates['.service_locator.tf.94Ei'] = $instance;
    }
}
