<?php

namespace ContainerNseTVN5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_He3sxJ5Service extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.service_locator.he3sxJ5' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'objectif' => ['privates', '.errored..service_locator.he3sxJ5.App\\Entity\\ObjectifSante', NULL, 'Cannot autowire service ".service_locator.he3sxJ5": it needs an instance of "App\\Entity\\ObjectifSante" but this type has been excluded in "config/services.yaml".'],
        ], [
            'em' => '?',
            'objectif' => 'App\\Entity\\ObjectifSante',
        ]);

        if (isset($container->privates['.service_locator.he3sxJ5'])) {
            return $container->privates['.service_locator.he3sxJ5'];
        }

        return $container->privates['.service_locator.he3sxJ5'] = $instance;
    }
}
