<?php

namespace ContainerNseTVN5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_VX8s8frService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.service_locator.VX8s8fr' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'proposition' => ['privates', '.errored..service_locator.VX8s8fr.App\\Entity\\PropositionReunion', NULL, 'Cannot autowire service ".service_locator.VX8s8fr": it needs an instance of "App\\Entity\\PropositionReunion" but this type has been excluded in "config/services.yaml".'],
        ], [
            'entityManager' => '?',
            'proposition' => 'App\\Entity\\PropositionReunion',
        ]);

        if (isset($container->privates['.service_locator.VX8s8fr'])) {
            return $container->privates['.service_locator.VX8s8fr'];
        }

        return $container->privates['.service_locator.VX8s8fr'] = $instance;
    }
}
