<?php

namespace ContainerNseTVN5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_FoPiE2jService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.service_locator.foPiE2j' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.foPiE2j'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'objectifSante' => ['privates', '.errored..service_locator.foPiE2j.App\\Entity\\ObjectifSante', NULL, 'Cannot autowire service ".service_locator.foPiE2j": it needs an instance of "App\\Entity\\ObjectifSante" but this type has been excluded in "config/services.yaml".'],
        ], [
            'objectifSante' => 'App\\Entity\\ObjectifSante',
        ]);
    }
}
