<?php

namespace ContainerNseTVN5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_961GAkService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.service_locator.961GAk_' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.961GAk_'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'csrfTokenManager' => ['privates', 'security.csrf.token_manager', 'getSecurity_Csrf_TokenManagerService', true],
            'groupeProjetRepository' => ['privates', '.errored.1DOHiVb', NULL, 'Cannot determine controller argument for "App\\Controller\\GroupeProjetController::ajaxFilter()": the $groupeProjetRepository argument is type-hinted with the non-existent class or interface: "App\\Controller\\GroupeProjetRepository". Did you forget to add a use statement?'],
        ], [
            'csrfTokenManager' => '?',
            'groupeProjetRepository' => '?',
        ]);
    }
}
