<?php

namespace ContainerNseTVN5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Q6yEmFAService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.service_locator.q6yEmFA' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'groupeProjet' => ['privates', '.errored..service_locator.q6yEmFA.App\\Entity\\GroupeProjet', NULL, 'Cannot autowire service ".service_locator.q6yEmFA": it needs an instance of "App\\Entity\\GroupeProjet" but this type has been excluded in "config/services.yaml".'],
        ], [
            'entityManager' => '?',
            'groupeProjet' => 'App\\Entity\\GroupeProjet',
        ]);

        if (isset($container->privates['.service_locator.q6yEmFA'])) {
            return $container->privates['.service_locator.q6yEmFA'];
        }

        return $container->privates['.service_locator.q6yEmFA'] = $instance;
    }
}
