<?php

namespace ContainerNseTVN5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_G1alqPJService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.service_locator.G1alqPJ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'propositionReunionRepository' => ['privates', 'App\\Repository\\PropositionReunionRepository', 'getPropositionReunionRepositoryService', true],
        ], [
            'entityManager' => '?',
            'propositionReunionRepository' => 'App\\Repository\\PropositionReunionRepository',
        ]);

        if (isset($container->privates['.service_locator.G1alqPJ'])) {
            return $container->privates['.service_locator.G1alqPJ'];
        }

        return $container->privates['.service_locator.G1alqPJ'] = $instance;
    }
}
