<?php

namespace ContainerNseTVN5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ONZDVoLService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.service_locator.ONZDVoL' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ONZDVoL'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'matiere' => ['privates', '.errored..service_locator.ONZDVoL.App\\Entity\\MatiereClasse', NULL, 'Cannot autowire service ".service_locator.ONZDVoL": it needs an instance of "App\\Entity\\MatiereClasse" but this type has been excluded in "config/services.yaml".'],
        ], [
            'matiere' => 'App\\Entity\\MatiereClasse',
        ]);
    }
}
