<?php

namespace ContainerNseTVN5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_FOVweQCService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.service_locator.FOVweQC' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.FOVweQC'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'propositionReunion' => ['privates', '.errored..service_locator.FOVweQC.App\\Entity\\PropositionReunion', NULL, 'Cannot autowire service ".service_locator.FOVweQC": it needs an instance of "App\\Entity\\PropositionReunion" but this type has been excluded in "config/services.yaml".'],
        ], [
            'propositionReunion' => 'App\\Entity\\PropositionReunion',
        ]);
    }
}
