<?php

namespace ContainerNseTVN5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_IKaCF9Service extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.service_locator.iKaCF9_' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'objectifSante' => ['privates', '.errored..service_locator.iKaCF9_.App\\Entity\\ObjectifSante', NULL, 'Cannot autowire service ".service_locator.iKaCF9_": it needs an instance of "App\\Entity\\ObjectifSante" but this type has been excluded in "config/services.yaml".'],
        ], [
            'entityManager' => '?',
            'objectifSante' => 'App\\Entity\\ObjectifSante',
        ]);

        if (isset($container->privates['.service_locator.iKaCF9_'])) {
            return $container->privates['.service_locator.iKaCF9_'];
        }

        return $container->privates['.service_locator.iKaCF9_'] = $instance;
    }
}
