<?php

namespace ContainerNseTVN5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPropositionReunion3Service extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.VX8s8fr.App\Entity\PropositionReunion' shared service.
     *
     * @return \App\Entity\PropositionReunion
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.VX8s8fr": it needs an instance of "App\\Entity\\PropositionReunion" but this type has been excluded in "config/services.yaml".');
    }
}
