<?php

namespace ContainerNseTVN5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getWorkloadServiceService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Service\WorkloadService' shared autowired service.
     *
     * @return \App\Service\WorkloadService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'WorkloadService.php';

        $a = ($container->privates['mailer.mailer'] ?? $container->load('getMailer_MailerService'));

        if (isset($container->privates['App\\Service\\WorkloadService'])) {
            return $container->privates['App\\Service\\WorkloadService'];
        }

        $instance = new \App\Service\WorkloadService($a, $container->getEnv('ADMIN_EMAIL'));

        if (isset($container->privates['App\\Service\\WorkloadService'])) {
            return $container->privates['App\\Service\\WorkloadService'];
        }

        return $container->privates['App\\Service\\WorkloadService'] = $instance;
    }
}
