<?php

namespace ContainerThetXAz;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_XbNLTlEService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.xbNLTlE' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.xbNLTlE'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'objectif' => ['privates', '.errored..service_locator.xbNLTlE.App\\Entity\\ObjectifSante', NULL, 'Cannot autowire service ".service_locator.xbNLTlE": it needs an instance of "App\\Entity\\ObjectifSante" but this type has been excluded in "config/services.yaml".'],
            'repo' => ['privates', 'App\\Repository\\SuiviBienEtreRepository', 'getSuiviBienEtreRepositoryService', true],
        ], [
            'objectif' => 'App\\Entity\\ObjectifSante',
            'repo' => 'App\\Repository\\SuiviBienEtreRepository',
        ]);
    }
}
