<?php

namespace ContainerThetXAz;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_1DOHiVbService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.1DOHiVb' shared service.
     *
     * @return \App\Controller\GroupeProjetRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot determine controller argument for "App\\Controller\\GroupeProjetController::ajaxFilter()": the $groupeProjetRepository argument is type-hinted with the non-existent class or interface: "App\\Controller\\GroupeProjetRepository". Did you forget to add a use statement?');
    }
}
