<?php

namespace ContainerThetXAz;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_VQ_NxadService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.VQ.Nxad' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.VQ.Nxad'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'matiereClasseRepository' => ['privates', 'App\\Repository\\MatiereClasseRepository', 'getMatiereClasseRepositoryService', true],
            'tacheRepository' => ['privates', 'App\\Repository\\TacheRepository', 'getTacheRepositoryService', true],
        ], [
            'matiereClasseRepository' => 'App\\Repository\\MatiereClasseRepository',
            'tacheRepository' => 'App\\Repository\\TacheRepository',
        ]);
    }
}
