<?php

namespace ContainerThetXAz;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_DvKPIRCService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.dvKPIRC' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.dvKPIRC'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'csrfTokenManager' => ['privates', 'security.csrf.token_manager', 'getSecurity_Csrf_TokenManagerService', true],
            'repo' => ['privates', 'App\\Repository\\SeanceRepository', 'getSeanceRepositoryService', true],
        ], [
            'csrfTokenManager' => '?',
            'repo' => 'App\\Repository\\SeanceRepository',
        ]);
    }
}
