<?php

namespace ContainerThetXAz;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_NOZCH1_Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.nOZCH1.' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.nOZCH1.'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'groupeProjetRepository' => ['privates', '.errored.VAVfs6_', NULL, 'Cannot determine controller argument for "App\\Controller\\GroupeProjetController::index()": the $groupeProjetRepository argument is type-hinted with the non-existent class or interface: "App\\Controller\\GroupeProjetRepository". Did you forget to add a use statement?'],
        ], [
            'groupeProjetRepository' => '?',
        ]);
    }
}
