<?php

namespace ContainerThetXAz;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_S71W8gDService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.s71W8gD' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.s71W8gD'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'matiereClasse' => ['privates', '.errored..service_locator.s71W8gD.App\\Entity\\MatiereClasse', NULL, 'Cannot autowire service ".service_locator.s71W8gD": it needs an instance of "App\\Entity\\MatiereClasse" but this type has been excluded in "config/services.yaml".'],
        ], [
            'matiereClasse' => 'App\\Entity\\MatiereClasse',
        ]);
    }
}
