<?php

namespace ContainerThetXAz;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_PeM8xv5Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.peM8xv5' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.peM8xv5'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'classe' => ['privates', '.errored..service_locator.peM8xv5.App\\Entity\\Classe', NULL, 'Cannot autowire service ".service_locator.peM8xv5": it needs an instance of "App\\Entity\\Classe" but this type has been excluded in "config/services.yaml".'],
            'seanceRepository' => ['privates', 'App\\Repository\\SeanceRepository', 'getSeanceRepositoryService', true],
            'tacheRepository' => ['privates', 'App\\Repository\\TacheRepository', 'getTacheRepositoryService', true],
        ], [
            'classe' => 'App\\Entity\\Classe',
            'seanceRepository' => 'App\\Repository\\SeanceRepository',
            'tacheRepository' => 'App\\Repository\\TacheRepository',
        ]);
    }
}
