<?php

namespace ContainerThetXAz;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_DQbfgToService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.DQbfgTo' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.DQbfgTo'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'classe' => ['privates', '.errored..service_locator.DQbfgTo.App\\Entity\\Classe', NULL, 'Cannot autowire service ".service_locator.DQbfgTo": it needs an instance of "App\\Entity\\Classe" but this type has been excluded in "config/services.yaml".'],
            'matiereClasseRepository' => ['privates', 'App\\Repository\\MatiereClasseRepository', 'getMatiereClasseRepositoryService', true],
        ], [
            'classe' => 'App\\Entity\\Classe',
            'matiereClasseRepository' => 'App\\Repository\\MatiereClasseRepository',
        ]);
    }
}
