<?php

namespace ContainerThetXAz;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_AGkzSRQService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.AGkzSRQ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'objectif' => ['privates', '.errored..service_locator.AGkzSRQ.App\\Entity\\ObjectifSante', NULL, 'Cannot autowire service ".service_locator.AGkzSRQ": it needs an instance of "App\\Entity\\ObjectifSante" but this type has been excluded in "config/services.yaml".'],
            'repo' => ['privates', 'App\\Repository\\SuiviBienEtreRepository', 'getSuiviBienEtreRepositoryService', true],
        ], [
            'em' => '?',
            'objectif' => 'App\\Entity\\ObjectifSante',
            'repo' => 'App\\Repository\\SuiviBienEtreRepository',
        ]);

        if (isset($container->privates['.service_locator.AGkzSRQ'])) {
            return $container->privates['.service_locator.AGkzSRQ'];
        }

        return $container->privates['.service_locator.AGkzSRQ'] = $instance;
    }
}
