<?php

namespace ContainerThetXAz;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_UcG0BiPService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ucG0BiP' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ucG0BiP'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'propositionRepo' => ['privates', 'App\\Repository\\PropositionReunionRepository', 'getPropositionReunionRepositoryService', true],
        ], [
            'propositionRepo' => 'App\\Repository\\PropositionReunionRepository',
        ]);
    }
}
