<?php

namespace ContainerThetXAz;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_DAuzb6FService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.dAuzb6F' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'matiere' => ['privates', '.errored..service_locator.dAuzb6F.App\\Entity\\MatiereClasse', NULL, 'Cannot autowire service ".service_locator.dAuzb6F": it needs an instance of "App\\Entity\\MatiereClasse" but this type has been excluded in "config/services.yaml".'],
        ], [
            'em' => '?',
            'matiere' => 'App\\Entity\\MatiereClasse',
        ]);

        if (isset($container->privates['.service_locator.dAuzb6F'])) {
            return $container->privates['.service_locator.dAuzb6F'];
        }

        return $container->privates['.service_locator.dAuzb6F'] = $instance;
    }
}
