<?php

namespace ContainerThetXAz;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getClasse4Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.DZhNVi_.App\Entity\Classe' shared service.
     *
     * @return \App\Entity\Classe
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.DZhNVi_": it needs an instance of "App\\Entity\\Classe" but this type has been excluded in "config/services.yaml".');
    }
}
