<?php

namespace ContainerThetXAz;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProgramGeneratorServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\ProgramGeneratorService' shared autowired service.
     *
     * @return \App\Service\ProgramGeneratorService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'ProgramGeneratorService.php';

        return $container->privates['App\\Service\\ProgramGeneratorService'] = new \App\Service\ProgramGeneratorService(($container->privates['App\\Repository\\MatiereClasseRepository'] ?? $container->load('getMatiereClasseRepositoryService')));
    }
}
