<?php

namespace ContainerThetXAz;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProgramGenerationServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\ProgramGenerationService' shared autowired service.
     *
     * @return \App\Service\ProgramGenerationService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'ProgramGenerationService.php';

        $a = ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container));

        if (isset($container->privates['App\\Service\\ProgramGenerationService'])) {
            return $container->privates['App\\Service\\ProgramGenerationService'];
        }

        $instance = new \App\Service\ProgramGenerationService(($container->privates['App\\Repository\\MatiereClasseRepository'] ?? $container->load('getMatiereClasseRepositoryService')), ($container->privates['App\\Repository\\SalleRepository'] ?? $container->load('getSalleRepositoryService')), ($container->privates['App\\Repository\\TacheRepository'] ?? $container->load('getTacheRepositoryService')), ($container->privates['App\\Repository\\SeanceRepository'] ?? $container->load('getSeanceRepositoryService')), $a);

        if (isset($container->privates['App\\Service\\ProgramGenerationService'])) {
            return $container->privates['App\\Service\\ProgramGenerationService'];
        }

        return $container->privates['App\\Service\\ProgramGenerationService'] = $instance;
    }
}
