<?php

namespace ContainerThetXAz;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPreferenceAlerteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.RmU.Xok.App\Entity\PreferenceAlerte' shared service.
     *
     * @return \App\Entity\PreferenceAlerte
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.RmU.Xok": it needs an instance of "App\\Entity\\PreferenceAlerte" but this type has been excluded in "config/services.yaml".');
    }
}
