<?php

namespace ContainerThetXAz;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getQuizStatsServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\QuizStatsService' shared autowired service.
     *
     * @return \App\Service\QuizStatsService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'QuizStatsService.php';

        return $container->privates['App\\Service\\QuizStatsService'] = new \App\Service\QuizStatsService(($container->privates['App\\Repository\\QuizAttemptRepository'] ?? $container->load('getQuizAttemptRepositoryService')), ($container->privates['App\\Repository\\QuizAttemptDetailRepository'] ?? $container->load('getQuizAttemptDetailRepositoryService')));
    }
}
