<?php

namespace ContainerThetXAz;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getQuizQuestionService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.YKwfAGa.App\Entity\QuizQuestion' shared service.
     *
     * @return \App\Entity\QuizQuestion
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.YKwfAGa": it needs an instance of "App\\Entity\\QuizQuestion" but this type has been excluded in "config/services.yaml".');
    }
}
