<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class User extends \App\Entity\User implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'classe' => [parent::class, 'classe', null, 16],
        "\0".parent::class."\0".'createdAt' => [parent::class, 'createdAt', null, 16],
        "\0".parent::class."\0".'dateDeNaissance' => [parent::class, 'dateDeNaissance', null, 16],
        "\0".parent::class."\0".'email' => [parent::class, 'email', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'idGroupe' => [parent::class, 'idGroupe', null, 16],
        "\0".parent::class."\0".'isVerified' => [parent::class, 'isVerified', null, 16],
        "\0".parent::class."\0".'nom' => [parent::class, 'nom', null, 16],
        "\0".parent::class."\0".'numTel' => [parent::class, 'numTel', null, 16],
        "\0".parent::class."\0".'objectifSantes' => [parent::class, 'objectifSantes', null, 16],
        "\0".parent::class."\0".'password' => [parent::class, 'password', null, 16],
        "\0".parent::class."\0".'prenom' => [parent::class, 'prenom', null, 16],
        "\0".parent::class."\0".'profilePic' => [parent::class, 'profilePic', null, 16],
        "\0".parent::class."\0".'role' => [parent::class, 'role', null, 16],
        "\0".parent::class."\0".'sexe' => [parent::class, 'sexe', null, 16],
        "\0".parent::class."\0".'taches' => [parent::class, 'taches', null, 16],
        'classe' => [parent::class, 'classe', null, 16],
        'createdAt' => [parent::class, 'createdAt', null, 16],
        'dateDeNaissance' => [parent::class, 'dateDeNaissance', null, 16],
        'email' => [parent::class, 'email', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'idGroupe' => [parent::class, 'idGroupe', null, 16],
        'isVerified' => [parent::class, 'isVerified', null, 16],
        'nom' => [parent::class, 'nom', null, 16],
        'numTel' => [parent::class, 'numTel', null, 16],
        'objectifSantes' => [parent::class, 'objectifSantes', null, 16],
        'password' => [parent::class, 'password', null, 16],
        'prenom' => [parent::class, 'prenom', null, 16],
        'profilePic' => [parent::class, 'profilePic', null, 16],
        'role' => [parent::class, 'role', null, 16],
        'sexe' => [parent::class, 'sexe', null, 16],
        'taches' => [parent::class, 'taches', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
