<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Classe extends \App\Entity\Classe implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'anneeuniversitaire' => [parent::class, 'anneeuniversitaire', null, 16],
        "\0".parent::class."\0".'description' => [parent::class, 'description', null, 16],
        "\0".parent::class."\0".'filiere' => [parent::class, 'filiere', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'matiereClasses' => [parent::class, 'matiereClasses', null, 16],
        "\0".parent::class."\0".'niveau' => [parent::class, 'niveau', null, 16],
        "\0".parent::class."\0".'nom' => [parent::class, 'nom', null, 16],
        "\0".parent::class."\0".'seances' => [parent::class, 'seances', null, 16],
        "\0".parent::class."\0".'user' => [parent::class, 'user', null, 16],
        'anneeuniversitaire' => [parent::class, 'anneeuniversitaire', null, 16],
        'description' => [parent::class, 'description', null, 16],
        'filiere' => [parent::class, 'filiere', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'matiereClasses' => [parent::class, 'matiereClasses', null, 16],
        'niveau' => [parent::class, 'niveau', null, 16],
        'nom' => [parent::class, 'nom', null, 16],
        'seances' => [parent::class, 'seances', null, 16],
        'user' => [parent::class, 'user', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
