<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class MatiereClasse extends \App\Entity\MatiereClasse implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'chargehoraire' => [parent::class, 'chargehoraire', null, 16],
        "\0".parent::class."\0".'classes' => [parent::class, 'classes', null, 16],
        "\0".parent::class."\0".'coefficient' => [parent::class, 'coefficient', null, 16],
        "\0".parent::class."\0".'description' => [parent::class, 'description', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'nom' => [parent::class, 'nom', null, 16],
        "\0".parent::class."\0".'prerequis' => [parent::class, 'prerequis', null, 16],
        "\0".parent::class."\0".'scorecomplexite' => [parent::class, 'scorecomplexite', null, 16],
        "\0".parent::class."\0".'seances' => [parent::class, 'seances', null, 16],
        'chargehoraire' => [parent::class, 'chargehoraire', null, 16],
        'classes' => [parent::class, 'classes', null, 16],
        'coefficient' => [parent::class, 'coefficient', null, 16],
        'description' => [parent::class, 'description', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'nom' => [parent::class, 'nom', null, 16],
        'prerequis' => [parent::class, 'prerequis', null, 16],
        'scorecomplexite' => [parent::class, 'scorecomplexite', null, 16],
        'seances' => [parent::class, 'seances', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
