# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
# config/services.yaml

parameters:
  profile_pics_directory: '%kernel.project_dir%/public/uploads/profile_pics'
  groq_api_key: '%env(string:GROQ_API_KEY)%'
  groq_model: '%env(string:GROQ_MODEL)%'
  brevo_api_key: '%env(string:BREVO_API_KEY)%'
  mail_from: '%env(string:MAIL_FROM)%'

services:
  _defaults:
    autowire: true
    autoconfigure: true
    bind:
      string $apiKey: '%groq_api_key%'
      string $model: '%groq_model%'
      string $brevoApiKey: '%brevo_api_key%'
      string $mailFrom: '%mail_from%'

  

  App\:
    resource: '../src/'
    exclude:
      - '../src/DependencyInjection/'
      - '../src/Entity/'
      - '../src/Kernel.php'
    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
