<?php

namespace ContainerA9MDZbm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_7KcJpRkService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.7KcJpRk' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.7KcJpRk'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'seance' => ['privates', '.errored..service_locator.7KcJpRk.App\\Entity\\Seance', NULL, 'Cannot autowire service ".service_locator.7KcJpRk": it needs an instance of "App\\Entity\\Seance" but this type has been excluded in "config/services.yaml".'],
        ], [
            'seance' => 'App\\Entity\\Seance',
        ]);
    }
}
