<?php

namespace ContainerA9MDZbm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_WG7apoDService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.WG7apoD' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'archivingService' => ['privates', 'App\\Service\\ArchivingService', 'getArchivingServiceService', true],
            'classe' => ['privates', '.errored..service_locator.WG7apoD.App\\Entity\\Classe', NULL, 'Cannot autowire service ".service_locator.WG7apoD": it needs an instance of "App\\Entity\\Classe" but this type has been excluded in "config/services.yaml".'],
        ], [
            'archivingService' => 'App\\Service\\ArchivingService',
            'classe' => 'App\\Entity\\Classe',
        ]);

        if (isset($container->privates['.service_locator.WG7apoD'])) {
            return $container->privates['.service_locator.WG7apoD'];
        }

        return $container->privates['.service_locator.WG7apoD'] = $instance;
    }
}
