<?php

namespace ContainerA9MDZbm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Y8WAidService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.y8WAid_' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'classe' => ['privates', '.errored..service_locator.y8WAid_.App\\Entity\\Classe', NULL, 'Cannot autowire service ".service_locator.y8WAid_": it needs an instance of "App\\Entity\\Classe" but this type has been excluded in "config/services.yaml".'],
            'workloadService' => ['privates', 'App\\Service\\WorkloadService', 'getWorkloadServiceService', true],
        ], [
            'classe' => 'App\\Entity\\Classe',
            'workloadService' => 'App\\Service\\WorkloadService',
        ]);

        if (isset($container->privates['.service_locator.y8WAid_'])) {
            return $container->privates['.service_locator.y8WAid_'];
        }

        return $container->privates['.service_locator.y8WAid_'] = $instance;
    }
}
