<?php

namespace ContainerA9MDZbm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_WIOp74Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.WIOp_74' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'preferenceAlerteRepository' => ['privates', 'App\\Repository\\PreferenceAlerteRepository', 'getPreferenceAlerteRepositoryService', true],
        ], [
            'entityManager' => '?',
            'preferenceAlerteRepository' => 'App\\Repository\\PreferenceAlerteRepository',
        ]);

        if (isset($container->privates['.service_locator.WIOp_74'])) {
            return $container->privates['.service_locator.WIOp_74'];
        }

        return $container->privates['.service_locator.WIOp_74'] = $instance;
    }
}
