<?php

namespace ContainerA9MDZbm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_HwDCUOHService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.HwDCUOH' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.HwDCUOH'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'proposition' => ['privates', '.errored..service_locator.HwDCUOH.App\\Entity\\PropositionReunion', NULL, 'Cannot autowire service ".service_locator.HwDCUOH": it needs an instance of "App\\Entity\\PropositionReunion" but this type has been excluded in "config/services.yaml".'],
        ], [
            'proposition' => 'App\\Entity\\PropositionReunion',
        ]);
    }
}
