<?php

namespace ContainerA9MDZbm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_N2XExrbService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.N2XExrb' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.N2XExrb'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'attemptRepository' => ['privates', 'App\\Repository\\QuizAttemptRepository', 'getQuizAttemptRepositoryService', true],
            'matiere' => ['privates', '.errored..service_locator.N2XExrb.App\\Entity\\MatiereClasse', NULL, 'Cannot autowire service ".service_locator.N2XExrb": it needs an instance of "App\\Entity\\MatiereClasse" but this type has been excluded in "config/services.yaml".'],
            'quizStatsService' => ['privates', 'App\\Service\\QuizStatsService', 'getQuizStatsServiceService', true],
        ], [
            'attemptRepository' => 'App\\Repository\\QuizAttemptRepository',
            'matiere' => 'App\\Entity\\MatiereClasse',
            'quizStatsService' => 'App\\Service\\QuizStatsService',
        ]);
    }
}
