<?php

namespace ContainerA9MDZbm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_DZhNViService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.DZhNVi_' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.DZhNVi_'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'classe' => ['privates', '.errored..service_locator.DZhNVi_.App\\Entity\\Classe', NULL, 'Cannot autowire service ".service_locator.DZhNVi_": it needs an instance of "App\\Entity\\Classe" but this type has been excluded in "config/services.yaml".'],
            'csrfTokenManager' => ['privates', 'security.csrf.token_manager', 'getSecurity_Csrf_TokenManagerService', true],
            'matiereClasseRepository' => ['privates', 'App\\Repository\\MatiereClasseRepository', 'getMatiereClasseRepositoryService', true],
        ], [
            'classe' => 'App\\Entity\\Classe',
            'csrfTokenManager' => '?',
            'matiereClasseRepository' => 'App\\Repository\\MatiereClasseRepository',
        ]);
    }
}
