<?php

namespace ContainerA9MDZbm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_O1HV1g_Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.o1HV1g.' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.o1HV1g.'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'preferenceAlerteRepository' => ['privates', 'App\\Repository\\PreferenceAlerteRepository', 'getPreferenceAlerteRepositoryService', true],
            'userRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
        ], [
            'preferenceAlerteRepository' => 'App\\Repository\\PreferenceAlerteRepository',
            'userRepository' => 'App\\Repository\\UserRepository',
        ]);
    }
}
