<?php

namespace ContainerA9MDZbm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_NNOK4CyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.NNOK4Cy' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'classe' => ['privates', '.errored..service_locator.NNOK4Cy.App\\Entity\\Classe', NULL, 'Cannot autowire service ".service_locator.NNOK4Cy": it needs an instance of "App\\Entity\\Classe" but this type has been excluded in "config/services.yaml".'],
            'generationService' => ['privates', 'App\\Service\\ProgramGenerationService', 'getProgramGenerationServiceService', true],
        ], [
            'classe' => 'App\\Entity\\Classe',
            'generationService' => 'App\\Service\\ProgramGenerationService',
        ]);

        if (isset($container->privates['.service_locator.NNOK4Cy'])) {
            return $container->privates['.service_locator.NNOK4Cy'];
        }

        return $container->privates['.service_locator.NNOK4Cy'] = $instance;
    }
}
