<?php

namespace ContainerA9MDZbm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_GMr90r8Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.GMr90r8' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.GMr90r8'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'classe' => ['privates', '.errored..service_locator.GMr90r8.App\\Entity\\Classe', NULL, 'Cannot autowire service ".service_locator.GMr90r8": it needs an instance of "App\\Entity\\Classe" but this type has been excluded in "config/services.yaml".'],
            'seanceRepository' => ['privates', 'App\\Repository\\SeanceRepository', 'getSeanceRepositoryService', true],
        ], [
            'classe' => 'App\\Entity\\Classe',
            'seanceRepository' => 'App\\Repository\\SeanceRepository',
        ]);
    }
}
