<?php

namespace ContainerA9MDZbm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMatiereClasse4Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.dAuzb6F.App\Entity\MatiereClasse' shared service.
     *
     * @return \App\Entity\MatiereClasse
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.dAuzb6F": it needs an instance of "App\\Entity\\MatiereClasse" but this type has been excluded in "config/services.yaml".');
    }
}
