<?php

namespace ContainerA9MDZbm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getObjectifSante4Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.he3sxJ5.App\Entity\ObjectifSante' shared service.
     *
     * @return \App\Entity\ObjectifSante
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.he3sxJ5": it needs an instance of "App\\Entity\\ObjectifSante" but this type has been excluded in "config/services.yaml".');
    }
}
