<?php

namespace ContainerA9MDZbm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getStatsServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\StatsService' shared autowired service.
     *
     * @return \App\Service\StatsService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'StatsService.php';

        return $container->privates['App\\Service\\StatsService'] = new \App\Service\StatsService();
    }
}
