<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNseTVN5\App_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNseTVN5/App_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerNseTVN5.legacy');

    return;
}

if (!\class_exists(App_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerNseTVN5\App_KernelTestDebugContainer::class, App_KernelTestDebugContainer::class, false);
}

return new \ContainerNseTVN5\App_KernelTestDebugContainer([
    'container.build_hash' => 'NseTVN5',
    'container.build_id' => 'caa01835',
    'container.build_time' => 1772675838,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNseTVN5');
