<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerThetXAz\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerThetXAz/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerThetXAz.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerThetXAz\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerThetXAz\App_KernelDevDebugContainer([
    'container.build_hash' => 'ThetXAz',
    'container.build_id' => '85a44742',
    'container.build_time' => 1772675591,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerThetXAz');
